[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "nspr", "atk", "cups", "dbus", "libdrm", "gtk3", "pango", "cairo", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb", "mesa", "expat", "libxkbcommon", "alsa-lib"]

[phases.install]
cmds = ["npm install", "npx playwright install chromium --with-deps"]

[start]
cmd = "npm start"
